### ISSUE TITLE
API Key not being used by TinyMCE

### ISSUE THREAD

**Issue by Drillan767** [SKLINET/strapi-plugin-tinymce#7]
Hello (I swear it's the last time)!

I have set a pre-existing API key for TinyMCE in the configuration page as said in the documentation, but I still have the "This domain is not registered with Tiny Cloud." message.

Also, when checking the network to see from where Tiny loads its plugins, I can see the following request being made: `https://cdn.tiny.cloud/1/no-api-key/tinymce/6.2.0-10/plugins/...` which makes me believe that the API key is not taken in account.

**Comment by Sklico** [comment]
Hi @Drillan767, please what version of plugin do you use ? This should be fixed in 1.0.2 version. There was problem with TinyMCE Editor component, which didn't rerender after successfully fetched API key in useEffect. Do you have this problem on 1.0.2 version ?

Thanks for info

**Comment by FieldMarshallVague** [comment]
I had the same issue switching back from using --watch-admin to my normal workflow. 

To fix it, I just deleted the '.cache' folder, re-ran 'yarn build' and then 'yarn develop' to run it again.

This is with my api key already set in the config/settings area from previous build.

**Comment by Drillan767** [comment]
Yes, I just upgraded Strapi to 4.4.1 and the plugin to 1.0.2 and I still have the error message

@FieldMarshallVague I also did that because Strapi decided to crash, but still have the problem

**Comment by FieldMarshallVague** [comment]
I also opened the debug console in chrome, so I could do a long-press hard refresh (i.e. long-click the refresh, choose 'hard refresh' from the ddrop down).  That was the final fix for me, since it clearly cached the 'no-api-key' value otherwise.

**Comment by Drillan767** [comment]
Ok it worked once I saved my API key again, I can close it now 😃
